In [2]:
import pandas as pd
import matplotlib.pyplot as plt

fuel = pd.read_csv('Trips.csv')
fuel.head()

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
0,Romford,35.3,100053.0,6.2,1.083658,3.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
1,Romford,31.3,100042.0,8.3,1.636097,3.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
2,7 kings,31.0,100036.0,2.6,0.517472,1.75,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
3,Goodmayes,36.6,100033.0,8.5,1.432891,3.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
4,Gidea park,37.1,100025.0,10.5,1.746187,5.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...

In [24]:
fuel['Tank'] = fuel['Tank'].str.split(' (', regex=False).str[0]

In [25]:
fuel['Cost'] = fuel['Cost'].round(2)
print(fuel['Cost'])

0       1.08
1       1.64
2       0.52
3       1.43
4       1.75
       ...
369    10.06
370    19.38
371      NaN
372      NaN
373      NaN
Name: Cost, Length: 373, dtype: float64

In [26]:
print(fuel['Mileage'])
print(fuel[fuel['Mileage'].isna()])

0      100053.0
1      100042.0
2      100036.0
3      100033.0
4      100025.0
         ...
369     94493.0
370         7.5
371         NaN
372         NaN
373         NaN
Name: Mileage, Length: 373, dtype: float64
    Location  MPG  Mileage  Miles  Cost  Estimated TFL Travel Date   Tank
371      Bow  NaN      NaN    NaN   NaN           15.0         NaN  99714
372     Home  NaN      NaN    NaN   NaN           15.0         NaN    NaN
373      NaN  NaN      NaN    NaN   NaN           15.0         NaN  99049

In [27]:
fuel.isna()

     Location    MPG  Mileage  Miles   Cost  Estimated TFL  Travel Date   Tank
0       False  False    False  False  False          False        False  False
1       False  False    False  False  False          False        False  False
2       False  False    False  False  False          False        False  False
3       False  False    False  False  False          False        False  False
4       False  False    False  False  False          False        False  False
..        ...    ...      ...    ...    ...            ...          ...    ...
369     False  False    False  False  False          False        False  False
370     False  False    False  False  False          False        False  False
371     False   True     True   True   True          False         True  False
372     False   True     True   True   True          False         True   True
373      True   True     True   True   True          False         True  False

[373 rows x 8 columns]

In [28]:
print(fuel[fuel.isna().any(axis=1)])

           Location   MPG  Mileage  Miles  Cost  Estimated TFL Travel Date  \
94           Ilford  12.4  99354.0    1.3  0.62           1.75         NaN
161  South Woodford  36.6  98284.0   37.4  6.03          15.00         NaN
327     Tesco bside  35.3  94967.0    8.0  1.37           3.50         NaN
339      RIC return  23.0  94841.0    2.0  0.52           3.50         NaN
371             Bow   NaN      NaN    NaN   NaN          15.00         NaN
372            Home   NaN      NaN    NaN   NaN          15.00         NaN
373             NaN   NaN      NaN    NaN   NaN          15.00         NaN

      Tank
94   99321
161  98097
327  94776
339  94776
371  99714
372    NaN
373  99049

In [29]:
incomplete = fuel[fuel['Travel Date'].isna() & fuel['Mileage'].notna()]
fuel[fuel['Mileage'].isin(incomplete['Mileage'])]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
94,Ilford,12.4,99354.0,1.3,0.62,1.75,NaN,99321
161,South Woodford,36.6,98284.0,37.4,6.03,15.00,NaN,98097
327,Tesco bside,35.3,94967.0,8.0,1.37,3.50,NaN,94776
339,RIC return,23.0,94841.0,2.0,0.52,3.50,NaN,94776

In [30]:
fuel = fuel.drop(277)

KeyError: '[277] not found in axis'

In [45]:
fuel.iloc[90:100, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
90,Ilford,12.4,99368.0,1.3,0.62,1.75,21/02/2026,99321
91,Ilford return,22.4,99366.0,7.5,1.97,7.00,21/02/2026,99321
92,RIC return,22.0,99359.0,2.7,0.72,3.50,21/02/2026,99321
93,Home,27.6,99356.0,1.5,0.32,1.75,20/02/2026,99321
94,Ilford,12.4,99354.0,1.3,0.62,1.75,NaN,99321
95,Home,27.4,99353.0,7.6,1.64,3.50,20/02/2026,99321
96,QM,32.8,99346.0,9.8,1.76,5.50,20/02/2026,99321
97,"Ilford, Walthamstow, gh, home",24.1,99336.0,11.5,2.81,5.50,19/02/2026,99321
98,Return from bside,26.6,99324.0,3.5,0.78,3.50,19/02/2026,99321
99,Bside,29.4,99321.0,5.4,1.08,3.50,19/02/2026,99049

In [49]:
fuel.loc[94, 'Travel Date'] = '20/02/2026'
fuel.iloc[93:96, :]

   Location   MPG  Mileage  Miles  Cost  Estimated TFL Travel Date   Tank
93     Home  27.6  99356.0    1.5  0.32           1.75  20/02/2026  99321
94   Ilford  12.4  99354.0    1.3  0.62           1.75  20/02/2026  99321
95     Home  27.4  99353.0    7.6  1.64           3.50  20/02/2026  99321

In [51]:
fuel.iloc[160:163, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
160,Home,26.4,98289.0,4.3,0.96,3.5,31/01/2026,98097
161,South Woodford,36.6,98284.0,37.4,6.03,15.0,NaN,98097
162,Rickmansworth,31.0,98247.0,43.7,8.31,15.0,31/01/2026,98097

In [52]:
fuel.loc[161, 'Travel Date'] = '31/01/2026'

In [54]:
fuel.iloc[325:328, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
326,Home from bside,33.6,94969.0,2.5,0.45,1.75,01/12/2025,94967
327,Tesco bside,35.3,94967.0,8.0,1.37,3.50,NaN,94776
328,Gidea park,38.1,94959.0,26.4,4.18,15.00,01/12/2025,94776

In [55]:
fuel.loc[327, 'Travel Date'] = '01/12/2025'

In [62]:
fuel.iloc[335:341, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
336,"Walthamstow, bside",22.9,94865.0,13.1,3.45,5.50,29/11/2025,94776
337,Bside,19.0,94851.0,3.0,0.95,1.75,29/11/2025,94776
338,South Woodford return,26.4,94848.0,4.4,1.01,3.50,29/11/2025,94776
339,RIC return,23.0,94841.0,2.0,0.52,3.50,NaN,94776
340,Bside return,26.6,94839.0,5.8,1.32,3.50,28/11/2025,94776
341,Home,30.0,94833.0,26.0,5.23,15.00,28/11/2025,94776

In [63]:
fuel.loc[339, 'Travel Date'] = '28/11/2025'

In [66]:
fuel[fuel.isna().any(axis=1)]

    Location  MPG  Mileage  Miles  Cost  Estimated TFL Travel Date   Tank
371      Bow  NaN      NaN    NaN   NaN           15.0         NaN  99714
372     Home  NaN      NaN    NaN   NaN           15.0         NaN    NaN
373      NaN  NaN      NaN    NaN   NaN           15.0         NaN  99049

In [75]:
fuel = fuel.drop([371, 372, 373])

In [76]:
fuel[fuel.isna().any(axis=1)]

Empty DataFrame
Columns: [Location, MPG, Mileage, Miles, Cost, Estimated TFL, Travel Date, Tank]
Index: []