In [4]:
import pandas as pd
import matplotlib.pyplot as plt

fuel = pd.read_csv('Trips.csv')
fuel.head()

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
0,Romford,35.3,100053.0,6.2,1.083658,3.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
1,Romford,31.3,100042.0,8.3,1.636097,3.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
2,7 kings,31.0,100036.0,2.6,0.517472,1.75,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
3,Goodmayes,36.6,100033.0,8.5,1.432891,3.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...
4,Gidea park,37.1,100025.0,10.5,1.746187,5.50,01/05/2026,99714 (https://www.notion.so/99714-31f37dd2ebd...

In [5]:
fuel['Tank'] = fuel['Tank'].str.split(' (', regex=False).str[0]

In [6]:
fuel['Cost'] = fuel['Cost'].round(2)
print(fuel['Cost'])

0       1.08
1       1.64
2       0.52
3       1.43
4       1.75
       ...
369    10.06
370    19.38
371      NaN
372      NaN
373      NaN
Name: Cost, Length: 374, dtype: float64

In [7]:
print(fuel['Mileage'])
print(fuel[fuel['Mileage'].isna()])

0      100053.0
1      100042.0
2      100036.0
3      100033.0
4      100025.0
         ...
369     94493.0
370         7.5
371         NaN
372         NaN
373         NaN
Name: Mileage, Length: 374, dtype: float64
    Location  MPG  Mileage  Miles  Cost  Estimated TFL Travel Date   Tank
371      Bow  NaN      NaN    NaN   NaN           15.0         NaN  99714
372     Home  NaN      NaN    NaN   NaN           15.0         NaN    NaN
373      NaN  NaN      NaN    NaN   NaN           15.0         NaN  99049

In [8]:
fuel.isna()

     Location    MPG  Mileage  Miles   Cost  Estimated TFL  Travel Date   Tank
0       False  False    False  False  False          False        False  False
1       False  False    False  False  False          False        False  False
2       False  False    False  False  False          False        False  False
3       False  False    False  False  False          False        False  False
4       False  False    False  False  False          False        False  False
..        ...    ...      ...    ...    ...            ...          ...    ...
369     False  False    False  False  False          False        False  False
370     False  False    False  False  False          False        False  False
371     False   True     True   True   True          False         True  False
372     False   True     True   True   True          False         True   True
373      True   True     True   True   True          False         True  False

[374 rows x 8 columns]

In [9]:
print(fuel[fuel.isna().any(axis=1)])

           Location   MPG  Mileage  Miles  Cost  Estimated TFL Travel Date  \
94           Ilford  12.4  99354.0    1.3  0.62           1.75         NaN
161  South Woodford  36.6  98284.0   37.4  6.03          15.00         NaN
277             NaN  31.3  95767.0    NaN   NaN          15.00         NaN
327     Tesco bside  35.3  94967.0    8.0  1.37           3.50         NaN
339      RIC return  23.0  94841.0    2.0  0.52           3.50         NaN
371             Bow   NaN      NaN    NaN   NaN          15.00         NaN
372            Home   NaN      NaN    NaN   NaN          15.00         NaN
373             NaN   NaN      NaN    NaN   NaN          15.00         NaN

      Tank
94   99321
161  98097
277    NaN
327  94776
339  94776
371  99714
372    NaN
373  99049

In [10]:
incomplete = fuel[fuel['Travel Date'].isna() & fuel['Mileage'].notna()]
fuel[fuel['Mileage'].isin(incomplete['Mileage'])]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
94,Ilford,12.4,99354.0,1.3,0.62,1.75,NaN,99321
161,South Woodford,36.6,98284.0,37.4,6.03,15.00,NaN,98097
277,NaN,31.3,95767.0,NaN,NaN,15.00,NaN,NaN
278,Newbury park,29.7,95767.0,2.1,0.43,1.75,12/12/2025,95765
327,Tesco bside,35.3,94967.0,8.0,1.37,3.50,NaN,94776
339,RIC return,23.0,94841.0,2.0,0.52,3.50,NaN,94776

In [11]:
fuel = fuel.drop(277)

In [12]:
fuel.iloc[90:100, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
90,Ilford,12.4,99368.0,1.3,0.62,1.75,21/02/2026,99321
91,Ilford return,22.4,99366.0,7.5,1.97,7.00,21/02/2026,99321
92,RIC return,22.0,99359.0,2.7,0.72,3.50,21/02/2026,99321
93,Home,27.6,99356.0,1.5,0.32,1.75,20/02/2026,99321
94,Ilford,12.4,99354.0,1.3,0.62,1.75,NaN,99321
95,Home,27.4,99353.0,7.6,1.64,3.50,20/02/2026,99321
96,QM,32.8,99346.0,9.8,1.76,5.50,20/02/2026,99321
97,"Ilford, Walthamstow, gh, home",24.1,99336.0,11.5,2.81,5.50,19/02/2026,99321
98,Return from bside,26.6,99324.0,3.5,0.78,3.50,19/02/2026,99321
99,Bside,29.4,99321.0,5.4,1.08,3.50,19/02/2026,99049

In [13]:
fuel.loc[94, 'Travel Date'] = '20/02/2026'
fuel.iloc[93:96, :]

   Location   MPG  Mileage  Miles  Cost  Estimated TFL Travel Date   Tank
93     Home  27.6  99356.0    1.5  0.32           1.75  20/02/2026  99321
94   Ilford  12.4  99354.0    1.3  0.62           1.75  20/02/2026  99321
95     Home  27.4  99353.0    7.6  1.64           3.50  20/02/2026  99321

In [14]:
fuel.iloc[160:163, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
160,Home,26.4,98289.0,4.3,0.96,3.5,31/01/2026,98097
161,South Woodford,36.6,98284.0,37.4,6.03,15.0,NaN,98097
162,Rickmansworth,31.0,98247.0,43.7,8.31,15.0,31/01/2026,98097

In [15]:
fuel.loc[161, 'Travel Date'] = '31/01/2026'

In [16]:
fuel.iloc[325:328, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
326,Home from bside,33.6,94969.0,2.5,0.45,1.75,01/12/2025,94967
327,Tesco bside,35.3,94967.0,8.0,1.37,3.50,NaN,94776
328,Gidea park,38.1,94959.0,26.4,4.18,15.00,01/12/2025,94776

In [17]:
fuel.loc[327, 'Travel Date'] = '01/12/2025'

In [18]:
fuel.iloc[335:341, :]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
336,"Walthamstow, bside",22.9,94865.0,13.1,3.45,5.50,29/11/2025,94776
337,Bside,19.0,94851.0,3.0,0.95,1.75,29/11/2025,94776
338,South Woodford return,26.4,94848.0,4.4,1.01,3.50,29/11/2025,94776
339,RIC return,23.0,94841.0,2.0,0.52,3.50,NaN,94776
340,Bside return,26.6,94839.0,5.8,1.32,3.50,28/11/2025,94776
341,Home,30.0,94833.0,26.0,5.23,15.00,28/11/2025,94776

In [19]:
fuel.loc[339, 'Travel Date'] = '28/11/2025'

In [20]:
fuel[fuel.isna().any(axis=1)]

    Location  MPG  Mileage  Miles  Cost  Estimated TFL Travel Date   Tank
371      Bow  NaN      NaN    NaN   NaN           15.0         NaN  99714
372     Home  NaN      NaN    NaN   NaN           15.0         NaN    NaN
373      NaN  NaN      NaN    NaN   NaN           15.0         NaN  99049

In [21]:
fuel = fuel.drop([371, 372, 373])

In [22]:
fuel[fuel.isna().any(axis=1)]

Empty DataFrame
Columns: [Location, MPG, Mileage, Miles, Cost, Estimated TFL, Travel Date, Tank]
Index: []

In [23]:
fuel['Travel Date'].dtype

In [24]:
fuel['Travel Date'] = pd.to_datetime(fuel['Travel Date'], format='%d/%m/%Y')

Now exploring a bug, where the line chart is spanning from the start to the middle, and not increasing in order

In [25]:
fuel = fuel.sort_values(by=['Mileage', 'Travel Date'], ascending=[True, True])

In [28]:
fuel[fuel['Mileage'] < 93000]

    Location   MPG  Mileage  Miles   Cost  Estimated TFL Travel Date   Tank
370     Home  30.3      7.5  99.57  19.38           15.0  2026-02-10  99049

In [33]:
fuel[(fuel['Travel Date'] < pd.to_datetime('2026-02-12')) & (fuel['Travel Date'] > pd.to_datetime('2026-02-09'))]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
370,Home,30.3,7.5,99.57,19.38,15.00,2026-02-10,99049
118,Bside return,23.7,99039.0,4.00,1.00,3.50,2026-02-10,98680
117,QM,30.0,99048.0,8.00,1.57,3.50,2026-02-10,98680
116,Bow,24.1,99049.0,1.70,0.42,1.75,2026-02-10,98680
115,Ilford return,27.1,99062.0,5.20,1.13,3.50,2026-02-11,99049
114,QM,30.0,99070.0,13.20,2.59,5.50,2026-02-11,99049
113,"Commercial road return, Stratford",19.3,99075.0,8.20,2.51,7.00,2026-02-11,99049
112,Gidea park,38.1,99104.0,26.00,4.02,15.00,2026-02-11,99049
111,Home,31.3,99115.0,10.50,1.98,5.50,2026-02-11,99049

In [35]:
fuel[fuel['Tank'] == '99049']

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
370,Home,30.3,7.5,99.57,19.38,15.00,2026-02-10,99049
115,Ilford return,27.1,99062.0,5.20,1.13,3.50,2026-02-11,99049
114,QM,30.0,99070.0,13.20,2.59,5.50,2026-02-11,99049
113,"Commercial road return, Stratford",19.3,99075.0,8.20,2.51,7.00,2026-02-11,99049
112,Gidea park,38.1,99104.0,26.00,4.02,15.00,2026-02-11,99049
111,Home,31.3,99115.0,10.50,1.98,5.50,2026-02-11,99049
110,St. Paul’s,25.4,99127.0,11.70,2.72,5.50,2026-02-12,99049
109,QM,24.5,99130.0,2.90,0.70,1.75,2026-02-12,99049
108,Home,25.9,99140.0,10.40,2.37,5.50,2026-02-12,99049
107,Bside return,25.9,99147.0,7.10,1.62,7.00,2026-02-12,99049
106,QM,26.4,99155.0,8.10,1.81,3.50,2026-02-13,99049
105,Home,28.2,99163.0,7.70,1.61,3.50,2026-02-13,99049
104,Commercial road,30.0,99176.0,12.30,2.42,5.50,2026-02-14,99049
103,Newbury park,35.7,99189.0,13.40,2.21,5.50,2026-02-14,99049
102,Dagenham,29.1,99193.0,3.60,0.73,3.50,2026-02-14,99049
101,Ocado enfield,34.0,99303.0,10.70,1.86,5.50,2026-02-19,99049
100,Home,33.6,99315.0,11.80,2.07,5.50,2026-02-19,99049
99,Bside,29.4,99321.0,5.40,1.08,3.50,2026-02-19,99049

In [37]:
fuel[fuel['Miles'] > 20]

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
370,Home,30.3,7.5,99.57,19.38,15.0,2026-02-10,99049
369,"Bside, around, Home, barnet return",27.6,94493.0,46.00,10.06,11.0,2025-11-21,94447
364,Home,32.1,94555.0,25.00,4.70,5.5,2025-11-23,94447
357,"Greenwich, Harold wood, gidea park, home",33.2,94667.0,58.00,10.54,15.0,2025-11-25,94566
353,Gidea Park,36.6,94717.0,25.50,4.20,15.0,2025-11-26,94566
...,...,...,...,...,...,...,...,...
82,Gide park return,34.0,99419.0,24.70,4.28,11.0,2026-02-23,99321
81,QM,25.6,99440.0,20.80,4.79,5.5,2026-02-24,99321
71,gidea park,40.9,99512.0,29.20,4.21,15.0,2026-02-25,99321
49,Gidea park return,34.0,99645.0,20.50,3.56,11.0,2026-03-05,99576
18,Gidea park return,32.9,99871.0,22.40,4.20,11.0,2026-04-15,99714

In [38]:
fuel['Mileage'].dtype

dtype('float64')

In [41]:
fuel[(fuel['Mileage'] > 99550) & (fuel['Mileage'] < 99600)].sort_values(by='Mileage')

,Location,MPG,Mileage,Miles,Cost,Estimated TFL,Travel Date,Tank
66,QM,30.0,99553.0,8.7,1.71,3.50,2026-02-27,99321
65,"Ilford lane, home",25.6,99568.0,14.9,3.43,5.50,2026-02-27,99321
64,Ilford,21.4,99569.0,1.7,0.47,1.75,2026-02-27,99321
63,Home,24.3,99571.0,1.5,0.36,1.75,2026-02-27,99321
62,Ilford,16.2,99572.0,1.3,0.47,1.75,2026-02-28,99321
61,Home,21.8,99574.0,1.5,0.41,1.75,2026-02-28,99321
60,Bside,20.6,99576.0,2.7,0.77,1.75,2026-03-02,99321
59,Home,24.5,99579.0,2.3,0.55,1.75,2026-03-02,99576
58,Ilford return,22.2,99580.0,2.8,0.74,3.50,2026-03-02,99576
57,GH,23.5,99583.0,1.5,0.38,1.75,2026-03-03,99576
56,QM,31.7,99592.0,8.9,1.66,3.50,2026-03-03,99576

In [27]:
fuel.to_csv('Trips_cleaned.csv', index=False)